---
title: "NCAA Project"
author: "Amber Duevel"
date: "9/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(dbplyr)
library(tidyverse)
library(dplyr)
```

```{r read in file, message = FALSE, warning = FALSE}
ace_vb<-read_csv("VB_aces-1.csv")
assists_vb<-read_csv("VB_assists-1.csv")
blocks_vb<-read_csv("VB_blocks-1.csv")
digs_vb<-read_csv("VB_digs-1.csv")
hit_perc_vb<-read_csv("VB_hit_perc-1.csv")
kills_vb<-read_csv("VB_kills-1.csv")
opp_hits_vb<-read_csv("VB_opp_hits-1.csv")
WL_perc_vb<-read_csv("VB_WL_perc-1.csv")

```

```{r join data}
NCAA_full_set <- ace_vb %>% right_join(assists_vb, by="Team") %>% 
  right_join(blocks_vb, by="Team") %>% 
  right_join(digs_vb, by="Team") %>% 
  right_join(hit_perc_vb, by="Team") %>% 
  right_join(kills_vb, by="Team") %>% 
  right_join(opp_hits_vb, by="Team") %>% 
  right_join(WL_perc_vb, by="Team")
```

```{r clean data}
names(NCAA_full_set)
NCAA_full_set <- NCAA_full_set %>% select(-c("...1.x", "...1.y", "S.y", "...1.x.x","S.x.x", "...1.y.y", "S.y.y", "...1.x.x.x", "S.x.x.x","...1.y.y.y", "S.y.y.y", "...1.x.x.x.x", "S","...1.y.y.y.y", "Rank.x", "Rank.y", "Rank.x.x", "Rank.y.y", "Rank.x.x.x", "Rank.y.y.y", "Rank.x.x.x.x", "Rank.y.y.y.y", "Kills.y")) 

NCAA_full_set = distinct(NCAA_full_set, Team, .keep_all = TRUE)
```

```{r rename}
NCAA_full_set <- rename(NCAA_full_set,c("Team_Name"="Team",
                                        "Sets"="S.x",
                                        "Aces"="Aces",
                                        "Per_Set_x"="Per Set.x",
                                        "Assists"="Assists", 
                                        "Per_Set_y"="Per Set.y",
                                        "Block_Solos"="Block Solos",
                                        "Block_Assists"="Block Assists",
                                        "Triple_Block"="TB",
                                        "Digs"="Digs",
                                        "Kills"="Kills.x",
                                        "Errors"="Errors", 
                                        "Total_Attacks"="Total Attacks",
                                        "Hitting_Percentage"="Pct..x",
                                        "Percentage_Set"="Per Set.y.y",
                                        "Opponents_Kill"="Opp Kills",
                                        "Opponents_Errors"="Opp Errors",
                                        "Opponents_Attacks"="Opp Attacks",
                                        "Opponents_Percentage"="Opp Pct",
                                        "Win"="W",
                                        "Lost"="L",
                                        "Win_Percentage"="Pct..y"))

```


```{r ace}
ace_lm = lm(Win_Percentage~Aces, data = NCAA_full_set)
summary(ace_lm)

ace_plot = ggplot(aes(x = Aces, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
ace_plot

par(mfrow = c(2,2))
plot(ace_lm)
```


```{r assists}
assists_lm = lm(Win_Percentage~Assists, data = NCAA_full_set)
summary(assists_lm)

assists_plot = ggplot(aes(x = Assists, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
assists_plot

par(mfrow = c(2,2))
plot(assists_lm)
```

```{r block solo}
block_solo_lm = lm(Win_Percentage~Block_Solos, data = NCAA_full_set)
summary(block_solo_lm)

block_solo_plot = ggplot(aes(x = Block_Solos, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
block_solo_plot

par(mfrow = c(2,2))
plot(block_solo_lm)
```

```{r block assists}
block_assists_lm = lm(Win_Percentage~Block_Assists, data = NCAA_full_set)
summary(block_assists_lm)

block_assists_plot = ggplot(aes(x = Block_Assists, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
block_assists_plot

par(mfrow = c(2,2))
plot(block_assists_lm)
```

```{r triple block}
triple_block_lm = lm(Win_Percentage~Triple_Block, data = NCAA_full_set)
summary(triple_block_lm)

triple_block_plot = ggplot(aes(x = Triple_Block, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
triple_block_plot

par(mfrow = c(2,2))
plot(triple_block_lm)
```

```{r digs}
digs_lm = lm(Win_Percentage~Digs, data = NCAA_full_set)
summary(digs_lm)

digs_plot = ggplot(aes(x = Digs, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
digs_plot

par(mfrow = c(2,2))
plot(digs_lm)
```

```{r kills}
kills_lm = lm(Win_Percentage~Kills, data = NCAA_full_set)
summary(kills_lm)

kills_plot = ggplot(aes(x = Kills, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
kills_plot

par(mfrow = c(2,2))
plot(kills_lm)
```

```{r errors}
errors_lm = lm(Win_Percentage~Errors, data = NCAA_full_set)
summary(errors_lm)

errors_plot = ggplot(aes(x = Errors, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
errors_plot

par(mfrow = c(2,2))
plot(errors_lm)
```

```{r total attacks}
total_attacks_lm = lm(Win_Percentage~Total_Attacks, data = NCAA_full_set)
summary(total_attacks_lm)

total_attacks_plot = ggplot(aes(x = Total_Attacks, y = Win_Percentage), data = NCAA_full_set) +
  geom_point() +
  geom_smooth(method = "lm")
total_attacks_plot

par(mfrow = c(2,2))
plot(total_attacks_lm)
```
